spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:ptcmss_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: update   # PROD an toàn, không drop data
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:false}
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
          connection:
            provider_disables_autocommit: true
          spring:
            jpa:
              properties:
                jakarta.persistence.query.timeout: 30000


  sql:
    init:
      mode: ${SQL_INIT_MODE:always}   # nếu bạn cần seed demo trên prod => set ENV SQL_INIT_MODE=always
      continue-on-error: false

server:
  port: ${SERVER_PORT:8080}
  address: 0.0.0.0

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_ENABLED:false}
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:false}

openapi:
  service:
    server: ${OPENAPI_SERVER:https://api.hethongvantai.site}

app:
  base-url: ${APP_BASE_URL:https://api.hethongvantai.site}
  frontend-url: ${APP_FRONTEND_URL:https://hethongvantai.site}
