spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/ptcmss_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  mail:
    host: smtp.gmail.com
    port: 587
    username: macuongthi012@gmail.com
    password: mdgkuccoaggtxlua
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

openapi:
  service:
    api-docs: Computer_sell
    server: http://localhost:8080
    title: Transport Application
    version: 1.0.0

payment:
  bank:
    code: ${PAYMENT_BANK_CODE:970423}  # Mã ngân hàng (TP bank)
    account:
      number: ${PAYMENT_BANK_ACCOUNT_NUMBER:00005505543}  # Số tài khoản nhận tiền
      name: ${PAYMENT_BANK_ACCOUNT_NAME:NGUYEN THUY HAU}  # Tên chủ tài khoản

vietqr:
  client-id: ${VIETQR_CLIENT_ID:2c533c20-80aa-41dc-b346-cde4bd3fb8de}  # Lấy từ https://my.vietqr.io/profile
  api-key: ${VIETQR_API_KEY:9db359c9-a744-4479-83b0-b8861178b081}      # Lấy từ https://my.vietqr.io/profile

# ===== JWT =====
jwt:
  accessKey: "bXktc3VwZXItc2VjcmV0LWFjY2Vzcy1rZXktMzItYnl0ZXMtb3ItbW9yZQ=="
  refreshKey: "bXktc3VwZXItc2VjcmV0LXJlZnJlc2gta2V5LTMyLWJ5dGVzLW9yLW1vcmU="
  secretsAreBase64: true
  expriMinutes: 15
  refreshExpriMinutes: 43200
  expireMinutes: 15
  refreshExpireMinutes: 43200

serpapi:
  key: ${SERPAPI_KEY:dummy-serp-api-key}

graphhopper:
  api-key: ${GRAPHHOPPER_API_KEY:dummy-graphhopper-api-key}
  # base-url: https://graphhopper.com/api/1
